version: '2'

volumes:
  assets:
  system:
  packs:
  db:
  redis:

services:

  db:
    restart: always
    image: postgres:9.6-alpine
    volumes:
      - db:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_PASSWORD: CHANGEME

  redis:
    restart: always
    image: redis:3-alpine
    volumes:
      - redis:/data:Z

  web:
    build:
      context: .
      dockerfile: conf/app/Dockerfile
    image: thegeekfactory/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    expose:
      - "3000"
    depends_on:
      - db
      - redis
    volumes:
      - assets:/mastodon/public/assets:z
      - system:/mastodon/public/system:z
      - packs:/mastodon/public/packs:z

  streaming:
    build:
      context: .
      dockerfile: conf/app/Dockerfile
    image: thegeekfactory/mastodon
    restart: always
    env_file: .env.production
    command: npm run start
    expose:
      - "4000"
    depends_on:
      - db
      - redis

  sidekiq:
    build:
      context: .
      dockerfile: conf/app/Dockerfile
    image: thegeekfactory/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq -q default -q mailers -q pull -q push
    depends_on:
      - db
      - redis
    volumes:
      - system:/mastodon/public/system:z

  nginx:
    restart: always
    image: nginx
    depends_on:
      - db
      - redis
      - web
    ports:
      - "8080:80"
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:z
      - ./mastodon/public:/home/mastodon/live/public:z
      - system:/home/mastodon/live/public/system:z
      - assets:/home/mastodon/live/public/assets:z
      - packs:/home/mastodon/live/public/packs:z
